{
 "title": "monitoring_dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "RPM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(ml_api_prediction_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Error Responses per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(ml_api_prediction_requests_total{status=\"error\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean predict weight",
   "type": "timeseries",
   "description": "Средний предсказанный вес моделью",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(ml_api_predicted_weight_kg_bucket[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean predicted dimensions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(ml_api_predicted_height_cm_bucket[1m]))",
     "legendFormat": "height"
    },
    {
     "expr": "histogram_quantile(0.5, rate(ml_api_predicted_length_cm_bucket[1m]))",
     "legendFormat": "lenght"
    },
    {
     "expr": "histogram_quantile(0.5, rate(ml_api_predicted_width_cm_bucket[1m]))",
     "legendFormat": "width"
    }
   ]
  }
 ]
}